In [1]:
!pip install nlp

You should consider upgrading via the '/Users/michaelmathew/opt/anaconda3/bin/python -m pip install --upgrade pip' command.


In [2]:


import nlp
import re
import collections
import numpy as np

from tensorflow import keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras import Sequential
from keras.layers import Embedding
from keras.layers import Bidirectional
from keras.layers import LSTM
from keras.layers import Dense



In [3]:
''' 
data = nlp.load_dataset('empathetic_dialogues')
'''

emotion_dataset = nlp.load_dataset('emotion')

Using custom data configuration default


In [4]:
emotion_dataset


{'train': Dataset(features: {'text': Value(dtype='string', id=None), 'label': Value(dtype='string', id=None)}, num_rows: 16000),
 'validation': Dataset(features: {'text': Value(dtype='string', id=None), 'label': Value(dtype='string', id=None)}, num_rows: 2000),
 'test': Dataset(features: {'text': Value(dtype='string', id=None), 'label': Value(dtype='string', id=None)}, num_rows: 2000)}

In [5]:
train_set = emotion_dataset['train']
validation_set = emotion_dataset['validation']
test_set = emotion_dataset['test']

''' 
train2={}
val2={}
test2={}
accepted_strings = ['surprised', 'embarrassed', 'caring', 'nostalgic','confident', 'disgusted', 'annoyed','embarrrassed', 'caring, ''lonely', 'guilty','anxious','impressed','jealous','anticipating', 'excited', 'trusting', 'devastated', 'content', 'faithful', 'afraid', 'sentimental', 'hopeful', 'proud','prepared','grateful','ashamed','furious','disappointed','apprehensive' ]


train2['prompt']=[]
val2['prompt']=[]
test2['prompt']=[]

train2['context']=[]
val2['context']=[]
test2['context']=[]
for xx in train_set:
    if (xx['context'] not in accepted_strings):
        train2['prompt'].append(xx['prompt'])
        train2['context'].append(xx['context'])



    
    
for xx in validation_set:
    if (xx['context'] not in accepted_strings):
        val2['prompt'].append(xx['prompt'])
        val2['context'].append(xx['context'])

        
for xx in test_set:
    if (xx['context'] not in accepted_strings):
        test2['prompt'].append(xx['prompt'])
        test2['context'].append(xx['context'])
        
        

train = train2
val = val2
test = test2
''' 
        

" \ntrain2={}\nval2={}\ntest2={}\naccepted_strings = ['surprised', 'embarrassed', 'caring', 'nostalgic','confident', 'disgusted', 'annoyed','embarrrassed', 'caring, ''lonely', 'guilty','anxious','impressed','jealous','anticipating', 'excited', 'trusting', 'devastated', 'content', 'faithful', 'afraid', 'sentimental', 'hopeful', 'proud','prepared','grateful','ashamed','furious','disappointed','apprehensive' ]\n\n\ntrain2['prompt']=[]\nval2['prompt']=[]\ntest2['prompt']=[]\n\ntrain2['context']=[]\nval2['context']=[]\ntest2['context']=[]\nfor xx in train_set:\n    if (xx['context'] not in accepted_strings):\n        train2['prompt'].append(xx['prompt'])\n        train2['context'].append(xx['context'])\n\n\n\n    \n    \nfor xx in validation_set:\n    if (xx['context'] not in accepted_strings):\n        val2['prompt'].append(xx['prompt'])\n        val2['context'].append(xx['context'])\n\n        \nfor xx in test_set:\n    if (xx['context'] not in accepted_strings):\n        test2['prompt'].

In [6]:

train_inputs, train_label = train_set['text'], train_set['label']
validation_inputs, validation_label = validation_set['text'], validation_set['label']
test_inputs, test_label = test_set['text'], test_set['label']


''' 
train__inputs, train_label = train_set['prompt'], train_set['context']
validation_inputs, validation_label = validation_set['prompt'], validation_set['context']
test_inputs, test_label = test_set['prompt'], test_set['context']
'''









" \ntrain__inputs, train_label = train_set['prompt'], train_set['context']\nvalidation_inputs, validation_label = validation_set['prompt'], validation_set['context']\ntest_inputs, test_label = test_set['prompt'], test_set['context']\n"

In [7]:


train_inputs[4], train_label[4]





('i am feeling grouchy', 'anger')

In [8]:
train_inputs[5], train_label[5]

('ive been feeling a little burdened lately wasnt sure why that was',
 'sadness')

In [9]:
train_inputs[6], train_label[6]

('ive been taking or milligrams or times recommended amount and ive fallen asleep a lot faster but i also feel like so funny',
 'surprise')

In [10]:
len(train_label)+len(test_label) + len(validation_label)

20000

In [11]:
unique_labels = set(train_label)
unique_labels

{'anger', 'fear', 'joy', 'love', 'sadness', 'surprise'}

In [12]:
collections.Counter(train_label)

Counter({'sadness': 4666,
         'anger': 2159,
         'love': 1304,
         'surprise': 572,
         'fear': 1937,
         'joy': 5362})

In [13]:
train_inputs[:3]

['i didnt feel humiliated',
 'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake',
 'im grabbing a minute to post i feel greedy wrong']

In [14]:
emotion_matched_label = dict((ex, rx) for rx, ex in enumerate(unique_labels))

numvauesfor_emotions = lambda labels: np.array([emotion_matched_label.get(ii) for ii in labels])
emotion_matched_label


{'joy': 0, 'love': 1, 'fear': 2, 'surprise': 3, 'anger': 4, 'sadness': 5}

In [15]:
numberofWords = 10000
lengthTwo = 50
truncating_and_padding_state = 'post'
tokenizer = Tokenizer( num_words = numberofWords)

In [16]:

tokenizer.fit_on_texts(train_inputs)

train_padded_inputs=pad_sequences(tokenizer.texts_to_sequences(train_inputs),maxlen=lengthTwo, padding=truncating_and_padding_state,truncating=truncating_and_padding_state)





trainids = numvauesfor_emotions(train_label)
trainids

array([5, 5, 4, ..., 0, 4, 5])

In [17]:

padded_validation_inputs = pad_sequences(tokenizer.texts_to_sequences(validation_inputs), maxlen=lengthTwo, padding=truncating_and_padding_state, truncating=truncating_and_padding_state)


valids = numvauesfor_emotions(validation_label)
valids

array([5, 5, 1, ..., 0, 0, 0])

In [18]:










  emotion_model = Sequential([
                  Embedding(output_dim=6, input_dim=numberofWords,  input_length = lengthTwo),
                  Bidirectional(LSTM(64, return_sequences=True)),
                  Bidirectional(LSTM(32)),
                  Dense(10, activation='relu'),
                  Dense(6, activation='softmax')
  ])

  emotion_model.compile(
                optimizer='adam',
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy']
  )







In [19]:





history = emotion_model.fit(
                  train_padded_inputs, trainids,
                  validation_data=(padded_validation_inputs, valids),
                  epochs=4
           
)

Epoch 1/4
500/500 [==============================] - 19s 29ms/step - loss: 1.3677 - accuracy: 0.4631 - val_loss: 0.8775 - val_accuracy: 0.7045
Epoch 2/4
500/500 [==============================] - 12s 23ms/step - loss: 0.6179 - accuracy: 0.7826 - val_loss: 0.5764 - val_accuracy: 0.7970
Epoch 3/4
500/500 [==============================] - 12s 23ms/step - loss: 0.3655 - accuracy: 0.8758 - val_loss: 0.4199 - val_accuracy: 0.8655
Epoch 4/4
500/500 [==============================] - 12s 24ms/step - loss: 0.2387 - accuracy: 0.9262 - val_loss: 0.3871 - val_accuracy: 0.8805


In [23]:



padded_test_inputs=pad_sequences(tokenizer.texts_to_sequences(test_inputs),maxlen=lengthTwo, padding=truncating_and_padding_state,truncating=truncating_and_padding_state)




testids = numvauesfor_emotions(test_label)
testids

array([5, 5, 5, ..., 0, 0, 2])

In [25]:

emotion_model.evaluate(padded_test_inputs, testids)

63/63 [==============================] - 1s 10ms/step - loss: 0.4062 - accuracy: 0.8715


[0.4062406122684479, 0.8715000152587891]

In [26]:
print('Input from testset:', test_inputs[3])
print('Actual Emotion from testset:', test_label[3])
predictVal = emotion_model.predict(np.expand_dims(padded_test_inputs[3], axis=0))[0]
label_matched_emotion = dict((rx, ex) for rx, ex in enumerate(unique_labels))
print('Predicted Emotion:', label_matched_emotion.get(np.argmax(predictVal)))

Input from testset: i left with my bouquet of red and yellow tulips under my arm feeling slightly more optimistic than when i arrived
Actual Emotion from testset: joy
Predicted Emotion: joy


In [33]:
xx=['that thing is terrifying!']
padxx=pad_sequences(tokenizer.texts_to_sequences(xx),maxlen=lengthTwo, padding=truncating_and_padding_state,truncating=truncating_and_padding_state)


print('Input from testset:', xx[0])
print('Actual Emotion from testset:', 'fear')

predictVal = emotion_model.predict(np.expand_dims(padxx[0], axis=0))[0]
label_matched_emotion = dict((rx, ex) for rx, ex in enumerate(unique_labels))
print('Predicted Emotion:', label_matched_emotion.get(np.argmax(predictVal)))

Input from testset: that thing is terrifying!
Actual Emotion from testset: fear
Predicted Emotion: fear


In [35]:
xx=['thah thing is terrifying!']
padxx=pad_sequences(tokenizer.texts_to_sequences(xx),maxlen=lengthTwo, padding=truncating_and_padding_state,truncating=truncating_and_padding_state)


print('Input from testset:', xx[0])
print('Actual Emotion from testset:', 'fear')

predictVal = emotion_model.predict(np.expand_dims(padxx[0], axis=0))[0]
label_matched_emotion = dict((rx, ex) for rx, ex in enumerate(unique_labels))
print('Predicted Emotion:', label_matched_emotion.get(np.argmax(predictVal)))

Input from testset: thah thing is terrifying!
Actual Emotion from testset: fear
Predicted Emotion: anger


In [ ]:
emotion_model.save("model.h5")